### ISSUE TITLE
Genome Nexus sometimes annotates SNV as DNP [issue #32]

### ISSUE THREAD

**Issue by ao508** [knowledgesystems/pipelines-scrum#519] opened 2021-03-18 16:14 UTC
https://github.com/genome-nexus/annotation-tools/issues/32

**Comment by averyniceday** [comment] 2021-03-25 15:23
I will take notes in this card for now. These notes can be moved to a google doc or something after the problem is fixed.

**Questions to Answer**
- [ ] Which Genome Nexus does Tom point to (and which version of server code does it run?)
- [ ] Is the problem after running the whole wrapper or just at a specific step?
- [ ] Is the problem in the server code, annotator code, VEP?
- [ ] For the annotator, what are the values in application.properties that Tom uses? Is this pre-built and provided?
- [ ] If this is specific to GENIE genome nexus because we're on a different version, is this something we want to propagate

**Setting Up a Genome Nexus Server**
Relatively easy following steps on the genome-nexus server page. Biggest challenge here is making sure you deploy the relevant server code (e.g hack for genie genome nexus vs master)

**Setting Up Annotation Wrapper**
We need to build an annotator jar for this, need a copy of the application.properties file that Tom uses. (Or what the default one is)

**Comment by averyniceday** [comment] 2021-03-25 15:33
**Setting Up a Genome Nexus Server**
Relatively easy following steps on the genome-nexus server page. Biggest challenge here is making sure you deploy the relevant server code (e.g hack for genie genome nexus vs master)

**Setting Up Annotation Wrapper**
We need to build an annotator jar for this, need a copy of the application.properties file that Tom uses. (Or what the default one is)

**Comment by averyniceday** [comment] 2021-03-25 15:33
Currently waiting for Tom to get back with the properties he uses for building his `annotator.jar`

**Comment by averyniceday** [comment] 2021-03-25 18:02
Beginning to think that this will be fixed with latest genome nexus server code.

**Comment by averyniceday** [comment] 2021-03-25 20:34
Confirmed that there's a difference in behavior in VariantTypeResolver (see [here](https://github.com/genome-nexus/genome-nexus/blob/b54b492815001d61b5c2f7b96185b89ec330e8e0/component/src/main/java/org/cbioportal/genome_nexus/component/annotation/VariantTypeResolver.java)) based on whether we are running a local VEP-backed vs ENSEMBL VEP-backed genome nexus

Beginning to trace how incoming requests to Genome Nexus are converted...

**Comment by averyniceday** [comment] 2021-03-26 14:51
Need to change this function if we want to fix it: 
`NotationConverter.genomicToEnsemblRestRegion`

**Comment by averyniceday** [comment] 2021-03-26 20:34
Example query (based on the codebase these should be equivalent, this happens around [here](https://github.com/genome-nexus/genome-nexus/blob/master/service/src/main/java/org/cbioportal/genome_nexus/service/internal/BaseVariantAnnotationServiceImpl.java#L230):

HGVSp: `11:g.69514130_69514131delinsTT`
http://grch37.rest.ensembl.org/vep/human/hgvs/11:g.69514130_69514131delinsTT?
 
Region: `11:69514130-69514131:1/TT`
http://grch37.rest.ensembl.org/vep/human/region/11:69514130-69514131:1/TT?

Look at the allele_string field of the two responses. One is `C/T` versus `TC/TT`. That gets fed into the resolvers listed below.
--------------------------------------------------------------------
`VariantTypeResolver.resolveVariantType()` [here](https://github.com/genome-nexus/genome-nexus/blob/master/component/src/main/java/org/cbioportal/genome_nexus/component/annotation/VariantTypeResolver.java#L37)

This uses ref/var allele length to decide (does not look at prefix) 
For HGVS, output would be: Ref C, Var T 
For Region, output would be: Ref TC, Var TT 

`GenomicLocationResolver.resolveReferenceAllele()/resolveVariantAllele()` [here](https://github.com/genome-nexus/genome-nexus/blob/master/component/src/main/java/org/cbioportal/genome_nexus/component/annotation/GenomicLocationResolver.java#L79)
This does a simple split of `allele_string` to determine ref/var alleles (which are then used by VariantTypeResolver). Also does not check for prefix.
For HGVS: looks at change C -> T, sees str length 1 and assigns SNP
For Region: looks at change TC -> TT, sees str length 2 and assigns DNP
---------------------------------------------------------------------
Not sure if we want to add something similar to the processing in the NotationConverter [here](https://github.com/genome-nexus/genome-nexus/blob/master/component/src/main/java/org/cbioportal/genome_nexus/component/annotation/NotationConverter.java#L118)

**Comment by averyniceday** [comment] 2021-03-26 20:40
this is the command I'm running to test:
```
sh annotation_suite_wrapper.sh -i=/<placeholder>/annotation-tools/tmp/ -o=/<placeholder>/annotation-tools/outputmp/ -m=/<placeholder>/annotation-tools/outputmp/randomfile.txt -c=randostr -s=anotherrandostring -p=/<placeholder>/annotation-tools/
```

**Closed** 2021-06-09 16:28 UTC
Labels: GENIE, Genome Nexus, help wanted
