### ISSUE TITLE
Have Mirrored Services on the New EKS Cluster 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#729] opened 2021-10-27 15:28 UTC
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Deploy new-SCLC, new-MSK, new-Private, new-triage to the EKS Cluster
Ensures we have the proper nodegroups setup

## Technical Description (How are we going to achieve the above)
Use the files we already have checked in with slight alterations and deploy. Tweak as necessary

**Comment by mandawilson** [comment] 2021-10-29 15:39
- [x] Config maps for deployments: all "applied" with SESSION_SERVICE_USER_PASSWORD for the public AWS session service and DB_HOST "new-privatedb" (changes not checked in)
- [x] all deployment files point to the public AWS session service url, `eks-msk-beta` was redeployed (no others have been deployed yet)
- [x] change urls of cbioportal instances in deployment files
- [x] use helm to setup and run triage persistence redis configuration (cache)
- [x] set up individual session redis configurations for each portal (session)
- [x] add to ingress NOTE: not deployed

- [x] make sure we have enough nodes to run portals on 
- [x] deploy individual session redises for each portals (session)  
- [x] apply ingress file
- [x] deploy portal instances
- [x] Keycloak config for each portal

**Comment by mandawilson** [comment] 2021-11-02 14:56
The problem is you can't actually login to any of these because pingid/google are not configured to work with these URLs.

**Closed as completed** 2021-11-15 15:18 UTC
Labels: backend-scrum
