### ISSUE TITLE
Define PDX Pipeline Workflow

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#947] opened 2022-09-13 14:26 UTC
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Understand Max's problem and come up with a workflow that ensures new studies get in 

```
 
#1 (Source)
lung_msk_pdx
mixed_cbe_baselgaj_JB_pdx
mixed_cbe_kunga_AK_pedpdx
mixed_cbe_rosenn_NR_labraf
mixed_cbe_rosenn_NR_prepdx
mixed_cbe_scaltrim_MS_ntrk
mixed_pdx_msk
msk_solid_heme
mskimpact
pilot_msk_melpcm
set_arbourk
set_chandars
set_cheny1
set_destance
set_edd
set_hoa
set_janjigiy
set_litop
set_mel
set_rielyg
set_rudinc
set_scaltrim
set_singers
set_weigeltb
temp_bic_janjigiy
temp_mel_resolvedruns
 
#2 (Destination)
mixed_pdx_msk
mixed_acc
set_chandars
set_cheny1
set_edd
set_hoa
set_litop
set_mel
set_singers
 ```

**Comment by mandawilson** [comment] 2022-09-16 09:57
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ find . -type d -name mixed_pdx_msk 
./crdb_pdx/mixed_pdx_msk
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ find . -type d -name mixed_acc
NOT FOUND
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ find . -type d -name set_chandars
./cmo-argos/ci/set_chandars
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ find . -type d -name set_cheny1
./cmo-argos/ci/set_cheny1
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ find . -type d -name set_edd
./cmo-argos/ci/set_edd
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ find . -type d -name set_hoa
./cmo-argos/ci/set_hoa
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ find . -type d -name set_litop
./cmo-argos/ci/set_litop
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ find . -type d -name set_mel
./crdb_pdx/mixed_pdx_msk/set_mel
./cmo-argos/ci/set_mel
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ find . -type d -name set_singers
./cmo-argos/ci/set_singers

**Comment by mandawilson** [comment] 2022-09-16 20:03
Nick Socci says:

Please do not allow anyone to add files to the autogenerated directories. This has caused problems in the past. If we really need to do this then we need to figure out a new set of rules. Whatever rules there existed where from the bic days and much has changed since then. 

I would need more details to understand what is the best way to go about this. But the safest way we have done before is when someone wants to add data is to “clone”/copy the auto-generated folder into a new study and work on that.

**Comment by mandawilson** [comment] 2022-09-20 16:32
Patient P-0040769 is meant to be pulled from 2 studies (mskimpact and set_rielyg) into mixed_pdx_msk.  It is in both source studies.  But not the destination study in the database.

mysql> select * from cancer_study where cancer_study_identifier='mskimpact';
| CANCER_STUDY_ID | CANCER_STUDY_IDENTIFIER | TYPE_OF_CANCER_ID | NAME                                   | DESCRIPTION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | PUBLIC | PMID | CITATION | GROUPS                     | STATUS | IMPORT_DATE         | REFERENCE_GENOME_ID |
|           49996 | mskimpact               | mixed             | MSK Clinical Sequencing Cohort (MSKCC) | Targeted sequencing of clinical cases via MSK-IMPACT, MSK-IMPACT-Heme, and MSK-ACCESS platforms. Data were generated and analyzed by the Molecular Diagnostics Service in the Department of Pathology. Please follow the <a href="http://cmo.mskcc.org/cmo/initiatives/msk-impact/">publication guidelines</a> when using these data in abstracts or journal articles. Manuscripts involving pan-cancer and other large analyses will undergo a biostatistical review prior to submission. If you would like assistance identifying a collaborator in Biostatistics, please contact Mithat Gonen (gonenm@mskcc.org). For questions regarding the results shown here, please contact Mike Berger (bergerm1@mskcc.org), Rose Brannon (brannona@mskcc.org), or Nikolaus Schultz (schultz@cbio.mskcc.org). <font color="red">These data are available to MSK investigators only and are not to be published or shared with anyone outside of MSK without permission.</font> |      1 | NULL | NULL     | MSKPUB;DMP;SOLITD;BERGERM1 |      0 | 2022-09-20 01:57:28 |                   1 |
1 row in set (0.00 sec)

mysql> select * from patient where cancer_study_id=49996 and stable_id='P-0040769';
+-------------+-----------+-----------------+
| INTERNAL_ID | STABLE_ID | CANCER_STUDY_ID |
+-------------+-----------+-----------------+
|   159382044 | P-0040769 |           49996 |
+-------------+-----------+-----------------+
1 row in set (0.06 sec)

mysql> select * from cancer_study where cancer_study_identifier='set_rielyg';
| CANCER_STUDY_ID | CANCER_STUDY_IDENTIFIER | TYPE_OF_CANCER_ID | NAME                                                 | DESCRIPTION                                                              | PUBLIC | PMID | CITATION | GROUPS                                 | STATUS | IMPORT_DATE         | REFERENCE_GENOME_ID |
|           32924 | set_rielyg              | mixed             | CMO Merged Study for Principal Investigator (rielyg) | [2020_12_07] Includes samples received at IGO for Project ID(s): 09652_S |      1 | NULL | NULL     | COMPONC;PRISM;VIALEA;RIELYG;XUEY;LITOP |      0 | 2020-12-09 00:00:00 |                   1 |
1 row in set (0.00 sec)

mysql> select * from patient where cancer_study_id=32924 and stable_id='P-0040769';
Empty set (0.00 sec)

mysql> select * from patient where cancer_study_id=32924 and stable_id='C-901DMD';
+-------------+-----------+-----------------+
| INTERNAL_ID | STABLE_ID | CANCER_STUDY_ID |
+-------------+-----------+-----------------+
|    95988330 | C-901DMD  |           32924 |
+-------------+-----------+-----------------+
1 row in set (0.00 sec)

**Comment by mandawilson** [comment] 2022-09-20 16:56
For set_rielyg log says:
Error, source path for set_rielyg could not be found, skipping...

We see subset_and_merge_crdb_pdx_studies.py assumes study directory is either in cmo-argos or it assumes it has a BIC id with 3 underscores which can be split to form the path to the subdirectory.  This doesn't work on cmo-argos studies.  Maybe use find?
subset_and_merge_crdb_pdx_studies.py
274     for data_source_directory in data_source_directories:
275         # find study by source id in root directory
276         source_path = os.path.join(data_source_directory, source_id)
277         if os.path.isdir(source_path):
278             source_paths.append(source_path)
279         # find study by assuming study id is path representation (first three underscores represent directory hierarchy)
280         split_source_id = source_id.split("_", 3)
281         source_path = os.path.join(data_source_directory, *split_source_id)
282         if os.path.isdir(source_path):
283             source_paths.append(source_path)
284     # only one path found, return value

**Comment by mandawilson** [comment] 2022-09-20 17:04
Source path not found for mskimpact too (why?)

**Comment by mandawilson** [comment] 2022-09-20 17:12
Study failed to import yesterday because of this:

2022-09-18 04:46:21 [main] INFO  org.mskcc.cbio.importer.Admin - java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Sample is not found in database (is it missing from clinical data file?): P-0012443-T01-IM5
        at org.mskcc.cbio.importer.util.MSKTransactionalScriptRunner.run(MSKTransactionalScriptRunner.java:80)
        at org.mskcc.cbio.importer.internal.ImporterImpl.loadCancerStudyStagingFiles(ImporterImpl.java:667)
        at org.mskcc.cbio.importer.internal.ImporterImpl.updateCancerStudy(ImporterImpl.java:193)
        at org.mskcc.cbio.importer.Admin.updateStudyData(Admin.java:521)
        at org.mskcc.cbio.importer.Admin.run(Admin.java:341)
        at org.mskcc.cbio.importer.Admin.main(Admin.java:850)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Sample is not found in database (is it missing from clinical data file?): P-0012443-T01-IM5
        at org.mskcc.cbio.portal.scripts.ImportProfileData.run(ImportProfileData.java:127)
        at org.mskcc.cbio.importer.util.MSKTransactionalScripts.run(MSKTransactionalScripts.java:86)
        at org.mskcc.cbio.importer.util.MSKTransactionalScriptRunner$1.doInTransaction(MSKTransactionalScriptRunner.java:88)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at org.mskcc.cbio.importer.util.MSKTransactionalScriptRunner.runInTransaction(MSKTransactionalScriptRunner.java:85)
        at org.mskcc.cbio.importer.util.MSKTransactionalScriptRunner.run(MSKTransactionalScriptRunner.java:77)
        ... 5 more
Caused by: java.lang.NullPointerException: Sample is not found in database (is it missing from clinical data file?): P-0012443-T01-IM5
        at org.mskcc.cbio.portal.scripts.ImportExtendedMutationData.missingSample(ImportExtendedMutationData.java:638)
        at org.mskcc.cbio.portal.scripts.ImportExtendedMutationData.getSequencedSamples(ImportExtendedMutationData.java:614)
        at org.mskcc.cbio.portal.scripts.ImportExtendedMutationData.processMAFHeader(ImportExtendedMutationData.java:600)
        at org.mskcc.cbio.portal.scripts.ImportExtendedMutationData.importData(ImportExtendedMutationData.java:128)
        at org.mskcc.cbio.portal.scripts.ImportProfileData.run(ImportProfileData.java:99)
        ... 10 more

**Comment by mandawilson** [comment] 2022-09-20 17:24
Some samples in the CRDB view have spaces in front.

**Closed as completed** 2022-10-11 17:36 UTC
Labels: backend-scrum
